version: '3.8'

services:
  db:
    image: postgres:12-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=hotline_user
      - POSTGRES_PASSWORD=hotline_user
      - POSTGRES_DB=hotline_dev
    networks:
      - backend_network
  server:
    build: ./server
    command: uvicorn app.main:app --reload --workers 1 --host 0.0.0.0 --port 5000
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgresql://hotline_user:hotline_user@db/hotline_dev
    volumes:
      - ./server/:/usr/src/app/
    depends_on:
      - db
    networks:
      - backend_network

volumes:
  postgres_data:

networks:
  backend_network:

